#!/usr/bin/env python3
"""Generate a 4-slot wall-mount flashlight holder as OpenSCAD and optional mesh export.

Default slot dimensions match the requested flashlight size:
- Diameter: 47.0 mm
- Depth: 38 mm

Usage:
  python3 scripts/generate_flashlight_mount.py
    python3 scripts/generate_flashlight_mount.py --mesh-format stl --output-mesh my_mount.stl
    python3 scripts/generate_flashlight_mount.py --no-mesh
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def compute_layout(
    slot_diameter: float,
    slot_wall_thickness: float,
    horizontal_gap: float,
    vertical_gap: float,
    margin: float,
    columns: int,
    rows: int,
) -> tuple[float, float, list[tuple[float, float]], float]:
    """Compute derived dimensions and center positions for slots."""

    outer_diameter = slot_diameter + (2.0 * slot_wall_thickness)
    plate_width = (columns * outer_diameter) + ((columns - 1) * horizontal_gap) + (2.0 * margin)
    plate_height = (rows * outer_diameter) + ((rows - 1) * vertical_gap) + (2.0 * margin)

    slot_centers = []
    for row in range(rows):
        for col in range(columns):
            x = margin + (outer_diameter / 2.0) + col * (outer_diameter + horizontal_gap)
            y = margin + (outer_diameter / 2.0) + row * (outer_diameter + vertical_gap)
            slot_centers.append((x, y))

    return plate_width, plate_height, slot_centers, outer_diameter


def generate_scad(
    slot_diameter: float,
    slot_depth: float,
    slot_wall_thickness: float,
    slot_bottom_thickness: float,
    horizontal_gap: float,
    vertical_gap: float,
    margin: float,
    plate_thickness: float,
    columns: int,
    rows: int,
) -> str:
    """Build the OpenSCAD source for a configurable 4-slot flashlight wall mount."""

    plate_width, plate_height, slot_centers, outer_diameter = compute_layout(
        slot_diameter=slot_diameter,
        slot_wall_thickness=slot_wall_thickness,
        horizontal_gap=horizontal_gap,
        vertical_gap=vertical_gap,
        margin=margin,
        columns=columns,
        rows=rows,
    )

    slot_points = "\n".join(
        f"        [{x:.3f}, {y:.3f}]," for (x, y) in slot_centers
    )
    support_rib_width = slot_wall_thickness
    support_height = outer_diameter * 0.5
    support_length = slot_depth + slot_bottom_thickness
    cup_y_center = plate_height - ((slot_depth + slot_bottom_thickness) / 2.0)

    return f"""// Auto-generated by generate_flashlight_mount.py
$fn = 120;

slot_diameter = {slot_diameter:.3f};
slot_depth = {slot_depth:.3f};
slot_wall = {slot_wall_thickness:.3f};
slot_bottom = {slot_bottom_thickness:.3f};
outer_d = slot_diameter + (2 * slot_wall);

plate_thickness = {plate_thickness:.3f};
plate_width = {plate_width:.3f};
plate_height = {plate_height:.3f};
support_rib_width = {support_rib_width:.3f};
support_height = {support_height:.3f};
support_length = {support_length:.3f};
cup_y_center = {cup_y_center:.3f};

slot_centers = [
{slot_points}
];

module flashlight_cup() {{
    // Rotated in wall_mount() so the flashlight axis is parallel to the wall.
    difference() {{
        cylinder(h = slot_depth + slot_bottom, d = outer_d, center = true);
        translate([0, 0, slot_bottom / 2])
            cylinder(h = slot_depth + 0.1, d = slot_diameter, center = true);
    }}
}}

module wall_mount() {{
    union() {{
        cube([plate_width, plate_height, plate_thickness]);

        for (p = slot_centers) {{
            translate([p[0] - (outer_d / 2), cup_y_center - (support_length / 2), plate_thickness])
                cube([support_rib_width, support_length, support_height]);

            translate([p[0] + (outer_d / 2) - support_rib_width, cup_y_center - (support_length / 2), plate_thickness])
                cube([support_rib_width, support_length, support_height]);

            translate([p[0], cup_y_center, plate_thickness + (outer_d / 2)])
                rotate([90, 0, 0])
                    flashlight_cup();
        }}
    }}
}}

wall_mount();
"""


def write_text_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def find_freecadcmd() -> str | None:
    """Find FreeCAD CLI path on PATH or common macOS install location."""

    found = shutil.which("freecadcmd")
    if found:
        return found

    fallback = Path("/Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd")
    if fallback.exists():
        return str(fallback)

    return None


def export_mesh_with_freecad(mesh_path: Path, params: dict[str, object]) -> bool:
    """Export 3MF/STL with FreeCAD by generating geometry directly in Part workbench."""

    freecadcmd = find_freecadcmd()
    if not freecadcmd:
        return False

    mesh_path.parent.mkdir(parents=True, exist_ok=True)

    exporter_source = f"""import json
import sys
import Part
import Mesh
from FreeCAD import Vector

params = json.loads({json.dumps(json.dumps(params))})

plate_width = float(params['plate_width'])
plate_height = float(params['plate_height'])
plate_thickness = float(params['plate_thickness'])

slot_diameter = float(params['slot_diameter'])
slot_depth = float(params['slot_depth'])
slot_bottom = float(params['slot_bottom_thickness'])
outer_diameter = float(params['outer_diameter'])
support_rib_width = float(params['support_rib_width'])
support_height = float(params['support_height'])
support_length = float(params['support_length'])
cup_y_center = float(params['cup_y_center'])

slot_centers = params['slot_centers']

body = Part.makeBox(plate_width, plate_height, plate_thickness)

for center in slot_centers:
    cx = float(center[0])

    left_support = Part.makeBox(support_rib_width, support_length, support_height)
    left_support.translate(Vector(cx - (outer_diameter / 2.0), cup_y_center - (support_length / 2.0), plate_thickness))
    body = body.fuse(left_support)

    right_support = Part.makeBox(support_rib_width, support_length, support_height)
    right_support.translate(Vector(cx + (outer_diameter / 2.0) - support_rib_width, cup_y_center - (support_length / 2.0), plate_thickness))
    body = body.fuse(right_support)

    cup_outer = Part.makeCylinder(outer_diameter / 2.0, slot_depth + slot_bottom)
    cup_inner = Part.makeCylinder(slot_diameter / 2.0, slot_depth + 0.1)
    cup_inner.translate(Vector(0, 0, slot_bottom))
    cup = cup_outer.cut(cup_inner)
    # Match OpenSCAD's center=true cup so Y-edge placement math is consistent.
    cup.translate(Vector(0, 0, -(slot_depth + slot_bottom) / 2.0))
    cup.rotate(Vector(0, 0, 0), Vector(1, 0, 0), 90)
    cup.translate(Vector(cx, cup_y_center, plate_thickness + (outer_diameter / 2.0)))
    body = body.fuse(cup)

mesh = Mesh.Mesh()
mesh.addFacets(body.tessellate(0.12))
mesh.write({json.dumps(str(mesh_path))})
"""

    with tempfile.NamedTemporaryFile("w", suffix="_freecad_export.py", delete=False) as tmp:
        tmp.write(exporter_source)
        script_path = Path(tmp.name)

    try:
        subprocess.run([freecadcmd, str(script_path)], check=True)
    finally:
        try:
            os.unlink(script_path)
        except OSError:
            pass

    return True


def export_mesh_with_openscad(scad_path: Path, mesh_path: Path) -> bool:
    """Fallback export using OpenSCAD CLI when available."""

    openscad_cmd = shutil.which("openscad")
    if not openscad_cmd:
        return False

    mesh_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [openscad_cmd, "-o", str(mesh_path), str(scad_path)]
    subprocess.run(cmd, check=True)
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a 4-slot wall-mount flashlight holder model."
    )
    parser.add_argument(
        "--output-mesh",
        default="flashlight_wall_mount.3mf",
        help="Output mesh path (.3mf recommended for Anycubic Slicer Next)",
    )
    parser.add_argument(
        "--mesh-format",
        choices=("3mf", "stl"),
        default="3mf",
        help="Mesh export format (default: 3mf)",
    )
    parser.add_argument("--no-mesh", action="store_true", help="Do not attempt mesh export")

    parser.add_argument("--slot-diameter", type=float, default=47.0)
    parser.add_argument("--slot-depth", type=float, default=38.0)
    parser.add_argument("--columns", type=int, default=4, help="Number of slot columns")
    parser.add_argument("--rows", type=int, default=1, help="Number of slot rows")

    parser.add_argument("--slot-wall-thickness", type=float, default=3.0)
    parser.add_argument("--slot-bottom-thickness", type=float, default=3.0)

    parser.add_argument("--horizontal-gap", type=float, default=12.0)
    parser.add_argument("--vertical-gap", type=float, default=12.0)
    parser.add_argument("--margin", type=float, default=14.0)

    parser.add_argument("--plate-thickness", type=float, default=6.0)

    return parser.parse_args()


def validate(args: argparse.Namespace) -> None:
    for key in (
        "slot_diameter",
        "slot_depth",
        "slot_wall_thickness",
        "slot_bottom_thickness",
        "horizontal_gap",
        "vertical_gap",
        "margin",
        "plate_thickness",
    ):
        if getattr(args, key) <= 0:
            raise ValueError(f"{key} must be > 0")

    if args.columns <= 0 or args.rows <= 0:
        raise ValueError("columns and rows must be > 0")

    if args.columns * args.rows != 4:
        raise ValueError("This mount is configured for exactly 4 flashlight slots (columns * rows must equal 4)")


def main() -> int:
    args = parse_args()

    try:
        validate(args)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    mesh_path = Path(args.output_mesh).expanduser().resolve()

    if mesh_path.suffix.lower() != f".{args.mesh_format}":
        mesh_path = mesh_path.with_suffix(f".{args.mesh_format}")

    plate_width, plate_height, slot_centers, outer_diameter = compute_layout(
        slot_diameter=args.slot_diameter,
        slot_wall_thickness=args.slot_wall_thickness,
        horizontal_gap=args.horizontal_gap,
        vertical_gap=args.vertical_gap,
        margin=args.margin,
        columns=args.columns,
        rows=args.rows,
    )

    scad_source = generate_scad(
        slot_diameter=args.slot_diameter,
        slot_depth=args.slot_depth,
        slot_wall_thickness=args.slot_wall_thickness,
        slot_bottom_thickness=args.slot_bottom_thickness,
        horizontal_gap=args.horizontal_gap,
        vertical_gap=args.vertical_gap,
        margin=args.margin,
        plate_thickness=args.plate_thickness,
        columns=args.columns,
        rows=args.rows,
    )

    if args.no_mesh:
        print("Skipped mesh export (--no-mesh set). No files written.")
        return 0

    try:
        export_params = {
            "plate_width": plate_width,
            "plate_height": plate_height,
            "plate_thickness": args.plate_thickness,
            "slot_diameter": args.slot_diameter,
            "slot_depth": args.slot_depth,
            "slot_bottom_thickness": args.slot_bottom_thickness,
            "outer_diameter": outer_diameter,
            "support_rib_width": args.slot_wall_thickness,
            "support_height": outer_diameter * 0.5,
            "support_length": args.slot_depth + args.slot_bottom_thickness,
            "cup_y_center": plate_height - ((args.slot_depth + args.slot_bottom_thickness) / 2.0),
            "slot_centers": slot_centers,
        }

        exported = export_mesh_with_freecad(mesh_path, export_params)
        if not exported:
            # OpenSCAD export requires a .scad input; keep it temporary so no scad file is persisted.
            with tempfile.NamedTemporaryFile("w", suffix=".scad", delete=False) as tmp_scad:
                tmp_scad.write(scad_source)
                temp_scad_path = Path(tmp_scad.name)

            try:
                exported = export_mesh_with_openscad(temp_scad_path, mesh_path)
            finally:
                try:
                    os.unlink(temp_scad_path)
                except OSError:
                    pass
    except subprocess.CalledProcessError as exc:
        print(
            f"Export failed (exit code {exc.returncode}).",
            file=sys.stderr,
        )
        return 1

    if exported:
        print(f"Wrote {args.mesh_format.upper()} model: {mesh_path}")
    else:
        print(f"Neither FreeCAD nor OpenSCAD CLI was found; {args.mesh_format.upper()} not exported.")
        print("Install FreeCAD or OpenSCAD and rerun this script to generate mesh files automatically.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
